// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/FyraLabs/subatomic/server/ent/repo"
	"github.com/FyraLabs/subatomic/server/ent/rpmpackage"
)

// RpmPackageCreate is the builder for creating a RpmPackage entity.
type RpmPackageCreate struct {
	config
	mutation *RpmPackageMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *RpmPackageCreate) SetName(v string) *RpmPackageCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetEpoch sets the "epoch" field.
func (_c *RpmPackageCreate) SetEpoch(v int) *RpmPackageCreate {
	_c.mutation.SetEpoch(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *RpmPackageCreate) SetVersion(v string) *RpmPackageCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetRelease sets the "release" field.
func (_c *RpmPackageCreate) SetRelease(v string) *RpmPackageCreate {
	_c.mutation.SetRelease(v)
	return _c
}

// SetArch sets the "arch" field.
func (_c *RpmPackageCreate) SetArch(v string) *RpmPackageCreate {
	_c.mutation.SetArch(v)
	return _c
}

// SetFilePath sets the "file_path" field.
func (_c *RpmPackageCreate) SetFilePath(v string) *RpmPackageCreate {
	_c.mutation.SetFilePath(v)
	return _c
}

// SetRepoID sets the "repo" edge to the Repo entity by ID.
func (_c *RpmPackageCreate) SetRepoID(id string) *RpmPackageCreate {
	_c.mutation.SetRepoID(id)
	return _c
}

// SetNillableRepoID sets the "repo" edge to the Repo entity by ID if the given value is not nil.
func (_c *RpmPackageCreate) SetNillableRepoID(id *string) *RpmPackageCreate {
	if id != nil {
		_c = _c.SetRepoID(*id)
	}
	return _c
}

// SetRepo sets the "repo" edge to the Repo entity.
func (_c *RpmPackageCreate) SetRepo(v *Repo) *RpmPackageCreate {
	return _c.SetRepoID(v.ID)
}

// Mutation returns the RpmPackageMutation object of the builder.
func (_c *RpmPackageCreate) Mutation() *RpmPackageMutation {
	return _c.mutation
}

// Save creates the RpmPackage in the database.
func (_c *RpmPackageCreate) Save(ctx context.Context) (*RpmPackage, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RpmPackageCreate) SaveX(ctx context.Context) *RpmPackage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RpmPackageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RpmPackageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RpmPackageCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RpmPackage.name"`)}
	}
	if _, ok := _c.mutation.Epoch(); !ok {
		return &ValidationError{Name: "epoch", err: errors.New(`ent: missing required field "RpmPackage.epoch"`)}
	}
	if v, ok := _c.mutation.Epoch(); ok {
		if err := rpmpackage.EpochValidator(v); err != nil {
			return &ValidationError{Name: "epoch", err: fmt.Errorf(`ent: validator failed for field "RpmPackage.epoch": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "RpmPackage.version"`)}
	}
	if _, ok := _c.mutation.Release(); !ok {
		return &ValidationError{Name: "release", err: errors.New(`ent: missing required field "RpmPackage.release"`)}
	}
	if _, ok := _c.mutation.Arch(); !ok {
		return &ValidationError{Name: "arch", err: errors.New(`ent: missing required field "RpmPackage.arch"`)}
	}
	if _, ok := _c.mutation.FilePath(); !ok {
		return &ValidationError{Name: "file_path", err: errors.New(`ent: missing required field "RpmPackage.file_path"`)}
	}
	return nil
}

func (_c *RpmPackageCreate) sqlSave(ctx context.Context) (*RpmPackage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RpmPackageCreate) createSpec() (*RpmPackage, *sqlgraph.CreateSpec) {
	var (
		_node = &RpmPackage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rpmpackage.Table, sqlgraph.NewFieldSpec(rpmpackage.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(rpmpackage.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Epoch(); ok {
		_spec.SetField(rpmpackage.FieldEpoch, field.TypeInt, value)
		_node.Epoch = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(rpmpackage.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Release(); ok {
		_spec.SetField(rpmpackage.FieldRelease, field.TypeString, value)
		_node.Release = value
	}
	if value, ok := _c.mutation.Arch(); ok {
		_spec.SetField(rpmpackage.FieldArch, field.TypeString, value)
		_node.Arch = value
	}
	if value, ok := _c.mutation.FilePath(); ok {
		_spec.SetField(rpmpackage.FieldFilePath, field.TypeString, value)
		_node.FilePath = value
	}
	if nodes := _c.mutation.RepoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rpmpackage.RepoTable,
			Columns: []string{rpmpackage.RepoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repo.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.repo_rpms = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RpmPackageCreateBulk is the builder for creating many RpmPackage entities in bulk.
type RpmPackageCreateBulk struct {
	config
	err      error
	builders []*RpmPackageCreate
}

// Save creates the RpmPackage entities in the database.
func (_c *RpmPackageCreateBulk) Save(ctx context.Context) ([]*RpmPackage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RpmPackage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RpmPackageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RpmPackageCreateBulk) SaveX(ctx context.Context) []*RpmPackage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RpmPackageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RpmPackageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
