// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/FyraLabs/subatomic/server/ent/predicate"
	"github.com/FyraLabs/subatomic/server/ent/rpmpackage"
)

// RpmPackageDelete is the builder for deleting a RpmPackage entity.
type RpmPackageDelete struct {
	config
	hooks    []Hook
	mutation *RpmPackageMutation
}

// Where appends a list predicates to the RpmPackageDelete builder.
func (rpd *RpmPackageDelete) Where(ps ...predicate.RpmPackage) *RpmPackageDelete {
	rpd.mutation.Where(ps...)
	return rpd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rpd *RpmPackageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, RpmPackageMutation](ctx, rpd.sqlExec, rpd.mutation, rpd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rpd *RpmPackageDelete) ExecX(ctx context.Context) int {
	n, err := rpd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rpd *RpmPackageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(rpmpackage.Table, sqlgraph.NewFieldSpec(rpmpackage.FieldID, field.TypeInt))
	if ps := rpd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rpd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rpd.mutation.done = true
	return affected, err
}

// RpmPackageDeleteOne is the builder for deleting a single RpmPackage entity.
type RpmPackageDeleteOne struct {
	rpd *RpmPackageDelete
}

// Where appends a list predicates to the RpmPackageDelete builder.
func (rpdo *RpmPackageDeleteOne) Where(ps ...predicate.RpmPackage) *RpmPackageDeleteOne {
	rpdo.rpd.mutation.Where(ps...)
	return rpdo
}

// Exec executes the deletion query.
func (rpdo *RpmPackageDeleteOne) Exec(ctx context.Context) error {
	n, err := rpdo.rpd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{rpmpackage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rpdo *RpmPackageDeleteOne) ExecX(ctx context.Context) {
	if err := rpdo.Exec(ctx); err != nil {
		panic(err)
	}
}
