// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/FyraLabs/subatomic/server/ent/predicate"
	"github.com/FyraLabs/subatomic/server/ent/repo"
	"github.com/FyraLabs/subatomic/server/ent/signingkey"
)

// SigningKeyUpdate is the builder for updating SigningKey entities.
type SigningKeyUpdate struct {
	config
	hooks    []Hook
	mutation *SigningKeyMutation
}

// Where appends a list predicates to the SigningKeyUpdate builder.
func (sku *SigningKeyUpdate) Where(ps ...predicate.SigningKey) *SigningKeyUpdate {
	sku.mutation.Where(ps...)
	return sku
}

// SetPrivateKey sets the "private_key" field.
func (sku *SigningKeyUpdate) SetPrivateKey(s string) *SigningKeyUpdate {
	sku.mutation.SetPrivateKey(s)
	return sku
}

// SetPublicKey sets the "public_key" field.
func (sku *SigningKeyUpdate) SetPublicKey(s string) *SigningKeyUpdate {
	sku.mutation.SetPublicKey(s)
	return sku
}

// SetName sets the "name" field.
func (sku *SigningKeyUpdate) SetName(s string) *SigningKeyUpdate {
	sku.mutation.SetName(s)
	return sku
}

// SetEmail sets the "email" field.
func (sku *SigningKeyUpdate) SetEmail(s string) *SigningKeyUpdate {
	sku.mutation.SetEmail(s)
	return sku
}

// AddRepoIDs adds the "repo" edge to the Repo entity by IDs.
func (sku *SigningKeyUpdate) AddRepoIDs(ids ...string) *SigningKeyUpdate {
	sku.mutation.AddRepoIDs(ids...)
	return sku
}

// AddRepo adds the "repo" edges to the Repo entity.
func (sku *SigningKeyUpdate) AddRepo(r ...*Repo) *SigningKeyUpdate {
	ids := make([]string, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return sku.AddRepoIDs(ids...)
}

// Mutation returns the SigningKeyMutation object of the builder.
func (sku *SigningKeyUpdate) Mutation() *SigningKeyMutation {
	return sku.mutation
}

// ClearRepo clears all "repo" edges to the Repo entity.
func (sku *SigningKeyUpdate) ClearRepo() *SigningKeyUpdate {
	sku.mutation.ClearRepo()
	return sku
}

// RemoveRepoIDs removes the "repo" edge to Repo entities by IDs.
func (sku *SigningKeyUpdate) RemoveRepoIDs(ids ...string) *SigningKeyUpdate {
	sku.mutation.RemoveRepoIDs(ids...)
	return sku
}

// RemoveRepo removes "repo" edges to Repo entities.
func (sku *SigningKeyUpdate) RemoveRepo(r ...*Repo) *SigningKeyUpdate {
	ids := make([]string, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return sku.RemoveRepoIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (sku *SigningKeyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, SigningKeyMutation](ctx, sku.sqlSave, sku.mutation, sku.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sku *SigningKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := sku.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (sku *SigningKeyUpdate) Exec(ctx context.Context) error {
	_, err := sku.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sku *SigningKeyUpdate) ExecX(ctx context.Context) {
	if err := sku.Exec(ctx); err != nil {
		panic(err)
	}
}

func (sku *SigningKeyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(signingkey.Table, signingkey.Columns, sqlgraph.NewFieldSpec(signingkey.FieldID, field.TypeString))
	if ps := sku.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sku.mutation.PrivateKey(); ok {
		_spec.SetField(signingkey.FieldPrivateKey, field.TypeString, value)
	}
	if value, ok := sku.mutation.PublicKey(); ok {
		_spec.SetField(signingkey.FieldPublicKey, field.TypeString, value)
	}
	if value, ok := sku.mutation.Name(); ok {
		_spec.SetField(signingkey.FieldName, field.TypeString, value)
	}
	if value, ok := sku.mutation.Email(); ok {
		_spec.SetField(signingkey.FieldEmail, field.TypeString, value)
	}
	if sku.mutation.RepoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   signingkey.RepoTable,
			Columns: []string{signingkey.RepoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: repo.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sku.mutation.RemovedRepoIDs(); len(nodes) > 0 && !sku.mutation.RepoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   signingkey.RepoTable,
			Columns: []string{signingkey.RepoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: repo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sku.mutation.RepoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   signingkey.RepoTable,
			Columns: []string{signingkey.RepoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: repo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, sku.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{signingkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	sku.mutation.done = true
	return n, nil
}

// SigningKeyUpdateOne is the builder for updating a single SigningKey entity.
type SigningKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SigningKeyMutation
}

// SetPrivateKey sets the "private_key" field.
func (skuo *SigningKeyUpdateOne) SetPrivateKey(s string) *SigningKeyUpdateOne {
	skuo.mutation.SetPrivateKey(s)
	return skuo
}

// SetPublicKey sets the "public_key" field.
func (skuo *SigningKeyUpdateOne) SetPublicKey(s string) *SigningKeyUpdateOne {
	skuo.mutation.SetPublicKey(s)
	return skuo
}

// SetName sets the "name" field.
func (skuo *SigningKeyUpdateOne) SetName(s string) *SigningKeyUpdateOne {
	skuo.mutation.SetName(s)
	return skuo
}

// SetEmail sets the "email" field.
func (skuo *SigningKeyUpdateOne) SetEmail(s string) *SigningKeyUpdateOne {
	skuo.mutation.SetEmail(s)
	return skuo
}

// AddRepoIDs adds the "repo" edge to the Repo entity by IDs.
func (skuo *SigningKeyUpdateOne) AddRepoIDs(ids ...string) *SigningKeyUpdateOne {
	skuo.mutation.AddRepoIDs(ids...)
	return skuo
}

// AddRepo adds the "repo" edges to the Repo entity.
func (skuo *SigningKeyUpdateOne) AddRepo(r ...*Repo) *SigningKeyUpdateOne {
	ids := make([]string, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return skuo.AddRepoIDs(ids...)
}

// Mutation returns the SigningKeyMutation object of the builder.
func (skuo *SigningKeyUpdateOne) Mutation() *SigningKeyMutation {
	return skuo.mutation
}

// ClearRepo clears all "repo" edges to the Repo entity.
func (skuo *SigningKeyUpdateOne) ClearRepo() *SigningKeyUpdateOne {
	skuo.mutation.ClearRepo()
	return skuo
}

// RemoveRepoIDs removes the "repo" edge to Repo entities by IDs.
func (skuo *SigningKeyUpdateOne) RemoveRepoIDs(ids ...string) *SigningKeyUpdateOne {
	skuo.mutation.RemoveRepoIDs(ids...)
	return skuo
}

// RemoveRepo removes "repo" edges to Repo entities.
func (skuo *SigningKeyUpdateOne) RemoveRepo(r ...*Repo) *SigningKeyUpdateOne {
	ids := make([]string, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return skuo.RemoveRepoIDs(ids...)
}

// Where appends a list predicates to the SigningKeyUpdate builder.
func (skuo *SigningKeyUpdateOne) Where(ps ...predicate.SigningKey) *SigningKeyUpdateOne {
	skuo.mutation.Where(ps...)
	return skuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (skuo *SigningKeyUpdateOne) Select(field string, fields ...string) *SigningKeyUpdateOne {
	skuo.fields = append([]string{field}, fields...)
	return skuo
}

// Save executes the query and returns the updated SigningKey entity.
func (skuo *SigningKeyUpdateOne) Save(ctx context.Context) (*SigningKey, error) {
	return withHooks[*SigningKey, SigningKeyMutation](ctx, skuo.sqlSave, skuo.mutation, skuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (skuo *SigningKeyUpdateOne) SaveX(ctx context.Context) *SigningKey {
	node, err := skuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (skuo *SigningKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := skuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (skuo *SigningKeyUpdateOne) ExecX(ctx context.Context) {
	if err := skuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (skuo *SigningKeyUpdateOne) sqlSave(ctx context.Context) (_node *SigningKey, err error) {
	_spec := sqlgraph.NewUpdateSpec(signingkey.Table, signingkey.Columns, sqlgraph.NewFieldSpec(signingkey.FieldID, field.TypeString))
	id, ok := skuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SigningKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := skuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, signingkey.FieldID)
		for _, f := range fields {
			if !signingkey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != signingkey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := skuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := skuo.mutation.PrivateKey(); ok {
		_spec.SetField(signingkey.FieldPrivateKey, field.TypeString, value)
	}
	if value, ok := skuo.mutation.PublicKey(); ok {
		_spec.SetField(signingkey.FieldPublicKey, field.TypeString, value)
	}
	if value, ok := skuo.mutation.Name(); ok {
		_spec.SetField(signingkey.FieldName, field.TypeString, value)
	}
	if value, ok := skuo.mutation.Email(); ok {
		_spec.SetField(signingkey.FieldEmail, field.TypeString, value)
	}
	if skuo.mutation.RepoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   signingkey.RepoTable,
			Columns: []string{signingkey.RepoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: repo.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := skuo.mutation.RemovedRepoIDs(); len(nodes) > 0 && !skuo.mutation.RepoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   signingkey.RepoTable,
			Columns: []string{signingkey.RepoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: repo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := skuo.mutation.RepoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   signingkey.RepoTable,
			Columns: []string{signingkey.RepoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: repo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SigningKey{config: skuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, skuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{signingkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	skuo.mutation.done = true
	return _node, nil
}
