[workspace]
members = ["crates/libsubatomic", "crates/satm", "crates/kiritan"]

# these are for performance optimizations, based on https://nnethercote.github.io/perf-book/build-configuration.html#optimization-level
# these options can take a while to compile (up to 5-10 minutes), so its really only necessary for production binaries.
# also look in .cargo/config.toml for info on microarchitecture optimizations.
[profile.release-optimized]
inherits = "release"

opt-level = 3
lto = "fat"
codegen-units = 1
debug = true

[package]
name = "subatomic"
version = "1.0.0"
edition = "2024"
license = "AGPL-3.0-or-later"

[dependencies]
axum = { version = "0.8.9", features = ["http2", "macros", "multipart"] }
crossbeam-channel = { workspace = true }
dotenvy = { workspace = true }
envy = "0.4.2"
futures-util = "0.3.33"
jsonwebtoken = { version = "11.0.0", features = ["aws_lc_rs"] }
libsubatomic = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
signal-hook = "0.4.4"
sqlx = { version = "0.9.0", features = ["postgres", "runtime-tokio"] }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = "0.7.19"
tracing = { workspace = true }
tracing-logfmt = { workspace = true }
tracing-subscriber = { workspace = true }

[workspace.dependencies]
crossbeam-channel = "0.5.16"
dotenvy = "0.15.7"
libsubatomic = { path = "./crates/libsubatomic/" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
thiserror = "2.0.19"
tokio = { version = "1.53.1", features = ["full"] }
tracing = "0.1.44"
tracing-logfmt = "0.3.7"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }


[lints]
workspace = true

[workspace.lints.clippy]
complexity = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
suspicious = { level = "warn", priority = -1 }
package = { level = "warn", priority = -1 }

disallowed-macros = "deny"
excessive-nesting = "warn"

assertions_on_result_states = "warn"
clone_on_ref_ptr = "warn"
create_dir = "warn"
empty_enum_variants_with_brackets = "warn"
empty_structs_with_brackets = "warn"
field_scoped_visibility_modifiers = "deny"
format_push_string = "warn"
get_unwrap = "warn"
if_then_some_else_none = "warn"
impl_trait_in_params = "warn"
infinite_loop = "deny"
let_underscore_must_use = "deny"
let_underscore_untyped = "warn"
needless_raw_strings = "warn"
rc_buffer = "warn"
rc_mutex = "deny"
redundant_type_annotations = "warn"
renamed_function_params = "warn"
rest_pat_in_fully_bound_structs = "warn"
semicolon_outside_block = "warn"
str_to_string = "warn"
string_lit_chars_any = "warn"
tests_outside_test_module = "warn"
todo = "warn"
try_err = "warn"
undocumented_unsafe_blocks = "deny"
unimplemented = "warn"
unneeded_field_pattern = "warn"
unwrap_in_result = "warn"
needless_for_each = "allow"
equatable_if_let = "allow"
