version: '3.8'

volumes:
  postgres-data:

services:
  subatomic:
    image: ghcr.io/fyralabs/subatomic:main
    restart: unless-stopped
    environment:
      - DATABASE_OPTIONS=host=db port=5432 user=postgres dbname=postgres password=password sslmode=disable
      - STORAGE_DIRECTORY=/storage
      # Set this in a .env file
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - .env
    volumes:
      - ./storage:/storage
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
