// Code generated by ent, DO NOT EDIT.

package rpmpackage

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/FyraLabs/subatomic/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// Epoch applies equality check predicate on the "epoch" field. It's identical to EpochEQ.
func Epoch(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldEpoch), v))
	})
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldVersion), v))
	})
}

// Release applies equality check predicate on the "release" field. It's identical to ReleaseEQ.
func Release(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRelease), v))
	})
}

// Arch applies equality check predicate on the "arch" field. It's identical to ArchEQ.
func Arch(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldArch), v))
	})
}

// FilePath applies equality check predicate on the "file_path" field. It's identical to FilePathEQ.
func FilePath(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFilePath), v))
	})
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldName), v))
	})
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.RpmPackage {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldName), v...))
	})
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.RpmPackage {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldName), v...))
	})
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldName), v))
	})
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldName), v))
	})
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldName), v))
	})
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldName), v))
	})
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldName), v))
	})
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldName), v))
	})
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldName), v))
	})
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldName), v))
	})
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldName), v))
	})
}

// EpochEQ applies the EQ predicate on the "epoch" field.
func EpochEQ(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldEpoch), v))
	})
}

// EpochNEQ applies the NEQ predicate on the "epoch" field.
func EpochNEQ(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldEpoch), v))
	})
}

// EpochIn applies the In predicate on the "epoch" field.
func EpochIn(vs ...string) predicate.RpmPackage {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldEpoch), v...))
	})
}

// EpochNotIn applies the NotIn predicate on the "epoch" field.
func EpochNotIn(vs ...string) predicate.RpmPackage {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldEpoch), v...))
	})
}

// EpochGT applies the GT predicate on the "epoch" field.
func EpochGT(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldEpoch), v))
	})
}

// EpochGTE applies the GTE predicate on the "epoch" field.
func EpochGTE(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldEpoch), v))
	})
}

// EpochLT applies the LT predicate on the "epoch" field.
func EpochLT(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldEpoch), v))
	})
}

// EpochLTE applies the LTE predicate on the "epoch" field.
func EpochLTE(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldEpoch), v))
	})
}

// EpochContains applies the Contains predicate on the "epoch" field.
func EpochContains(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldEpoch), v))
	})
}

// EpochHasPrefix applies the HasPrefix predicate on the "epoch" field.
func EpochHasPrefix(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldEpoch), v))
	})
}

// EpochHasSuffix applies the HasSuffix predicate on the "epoch" field.
func EpochHasSuffix(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldEpoch), v))
	})
}

// EpochEqualFold applies the EqualFold predicate on the "epoch" field.
func EpochEqualFold(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldEpoch), v))
	})
}

// EpochContainsFold applies the ContainsFold predicate on the "epoch" field.
func EpochContainsFold(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldEpoch), v))
	})
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldVersion), v))
	})
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldVersion), v))
	})
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.RpmPackage {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldVersion), v...))
	})
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.RpmPackage {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldVersion), v...))
	})
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldVersion), v))
	})
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldVersion), v))
	})
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldVersion), v))
	})
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldVersion), v))
	})
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldVersion), v))
	})
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldVersion), v))
	})
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldVersion), v))
	})
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldVersion), v))
	})
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldVersion), v))
	})
}

// ReleaseEQ applies the EQ predicate on the "release" field.
func ReleaseEQ(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRelease), v))
	})
}

// ReleaseNEQ applies the NEQ predicate on the "release" field.
func ReleaseNEQ(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldRelease), v))
	})
}

// ReleaseIn applies the In predicate on the "release" field.
func ReleaseIn(vs ...string) predicate.RpmPackage {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldRelease), v...))
	})
}

// ReleaseNotIn applies the NotIn predicate on the "release" field.
func ReleaseNotIn(vs ...string) predicate.RpmPackage {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldRelease), v...))
	})
}

// ReleaseGT applies the GT predicate on the "release" field.
func ReleaseGT(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldRelease), v))
	})
}

// ReleaseGTE applies the GTE predicate on the "release" field.
func ReleaseGTE(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldRelease), v))
	})
}

// ReleaseLT applies the LT predicate on the "release" field.
func ReleaseLT(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldRelease), v))
	})
}

// ReleaseLTE applies the LTE predicate on the "release" field.
func ReleaseLTE(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldRelease), v))
	})
}

// ReleaseContains applies the Contains predicate on the "release" field.
func ReleaseContains(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldRelease), v))
	})
}

// ReleaseHasPrefix applies the HasPrefix predicate on the "release" field.
func ReleaseHasPrefix(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldRelease), v))
	})
}

// ReleaseHasSuffix applies the HasSuffix predicate on the "release" field.
func ReleaseHasSuffix(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldRelease), v))
	})
}

// ReleaseEqualFold applies the EqualFold predicate on the "release" field.
func ReleaseEqualFold(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldRelease), v))
	})
}

// ReleaseContainsFold applies the ContainsFold predicate on the "release" field.
func ReleaseContainsFold(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldRelease), v))
	})
}

// ArchEQ applies the EQ predicate on the "arch" field.
func ArchEQ(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldArch), v))
	})
}

// ArchNEQ applies the NEQ predicate on the "arch" field.
func ArchNEQ(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldArch), v))
	})
}

// ArchIn applies the In predicate on the "arch" field.
func ArchIn(vs ...string) predicate.RpmPackage {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldArch), v...))
	})
}

// ArchNotIn applies the NotIn predicate on the "arch" field.
func ArchNotIn(vs ...string) predicate.RpmPackage {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldArch), v...))
	})
}

// ArchGT applies the GT predicate on the "arch" field.
func ArchGT(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldArch), v))
	})
}

// ArchGTE applies the GTE predicate on the "arch" field.
func ArchGTE(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldArch), v))
	})
}

// ArchLT applies the LT predicate on the "arch" field.
func ArchLT(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldArch), v))
	})
}

// ArchLTE applies the LTE predicate on the "arch" field.
func ArchLTE(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldArch), v))
	})
}

// ArchContains applies the Contains predicate on the "arch" field.
func ArchContains(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldArch), v))
	})
}

// ArchHasPrefix applies the HasPrefix predicate on the "arch" field.
func ArchHasPrefix(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldArch), v))
	})
}

// ArchHasSuffix applies the HasSuffix predicate on the "arch" field.
func ArchHasSuffix(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldArch), v))
	})
}

// ArchEqualFold applies the EqualFold predicate on the "arch" field.
func ArchEqualFold(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldArch), v))
	})
}

// ArchContainsFold applies the ContainsFold predicate on the "arch" field.
func ArchContainsFold(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldArch), v))
	})
}

// FilePathEQ applies the EQ predicate on the "file_path" field.
func FilePathEQ(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFilePath), v))
	})
}

// FilePathNEQ applies the NEQ predicate on the "file_path" field.
func FilePathNEQ(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldFilePath), v))
	})
}

// FilePathIn applies the In predicate on the "file_path" field.
func FilePathIn(vs ...string) predicate.RpmPackage {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldFilePath), v...))
	})
}

// FilePathNotIn applies the NotIn predicate on the "file_path" field.
func FilePathNotIn(vs ...string) predicate.RpmPackage {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldFilePath), v...))
	})
}

// FilePathGT applies the GT predicate on the "file_path" field.
func FilePathGT(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldFilePath), v))
	})
}

// FilePathGTE applies the GTE predicate on the "file_path" field.
func FilePathGTE(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldFilePath), v))
	})
}

// FilePathLT applies the LT predicate on the "file_path" field.
func FilePathLT(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldFilePath), v))
	})
}

// FilePathLTE applies the LTE predicate on the "file_path" field.
func FilePathLTE(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldFilePath), v))
	})
}

// FilePathContains applies the Contains predicate on the "file_path" field.
func FilePathContains(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldFilePath), v))
	})
}

// FilePathHasPrefix applies the HasPrefix predicate on the "file_path" field.
func FilePathHasPrefix(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldFilePath), v))
	})
}

// FilePathHasSuffix applies the HasSuffix predicate on the "file_path" field.
func FilePathHasSuffix(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldFilePath), v))
	})
}

// FilePathEqualFold applies the EqualFold predicate on the "file_path" field.
func FilePathEqualFold(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldFilePath), v))
	})
}

// FilePathContainsFold applies the ContainsFold predicate on the "file_path" field.
func FilePathContainsFold(v string) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldFilePath), v))
	})
}

// HasRepo applies the HasEdge predicate on the "repo" edge.
func HasRepo() predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RepoTable, RepoFieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RepoTable, RepoColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRepoWith applies the HasEdge predicate on the "repo" edge with a given conditions (other predicates).
func HasRepoWith(preds ...predicate.Repo) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RepoInverseTable, RepoFieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RepoTable, RepoColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RpmPackage) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RpmPackage) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RpmPackage) predicate.RpmPackage {
	return predicate.RpmPackage(func(s *sql.Selector) {
		p(s.Not())
	})
}
