CREATE TABLE IF NOT EXISTS keys (
    id      TEXT PRIMARY KEY,
    userid  TEXT NOT NULL,
    pri     TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS repos (
    id      SERIAL PRIMARY KEY,
    name    TEXT UNIQUE NOT NULL,
    key_id  TEXT REFERENCES keys(id) ON DELETE RESTRICT
);
