basePath: /
definitions:
  main.createKeyPayload:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    required:
    - email
    - id
    - name
    type: object
  main.fullKeyResponse:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      public_key:
        type: string
    type: object
  types.CreateRepoPayload:
    properties:
      id:
        type: string
      type:
        enum:
        - rpm
        type: string
    required:
    - id
    - type
    type: object
  types.ErrResponse:
    properties:
      code:
        description: application-specific error code
        type: integer
      error:
        description: application-level error message, for debugging
        type: string
      status:
        description: user-level status message
        type: string
    type: object
  types.KeyResponse:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  types.RepoResponse:
    properties:
      id:
        type: string
      type:
        type: string
    type: object
  types.RpmResponse:
    properties:
      arch:
        type: string
      epoch:
        type: integer
      file_path:
        type: string
      id:
        type: integer
      name:
        type: string
      release:
        type: string
      version:
        type: string
    type: object
info:
  contact: {}
  description: A modern package delivery server.
  license:
    name: GPL3
    url: https://choosealicense.com/licenses/gpl-3.0/
  title: Subatomic
  version: "1.0"
paths:
  /keys:
    get:
      description: get keys
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.KeyResponse'
            type: array
      summary: Get all keys
      tags:
      - keys
    post:
      consumes:
      - application/json
      description: create key
      parameters:
      - description: options for the new key
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.createKeyPayload'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/types.ErrResponse'
      summary: Create a new key
      tags:
      - keys
  /keys/{id}:
    get:
      consumes:
      - application/json
      description: get key
      parameters:
      - description: id for the key
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/types.ErrResponse'
      summary: Get a key
      tags:
      - keys
  /repos:
    get:
      description: get repos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.RepoResponse'
            type: array
      summary: Get all repos
      tags:
      - repos
    post:
      consumes:
      - application/json
      description: create repo
      parameters:
      - description: options for the new repository
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/types.CreateRepoPayload'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/types.ErrResponse'
      summary: Create a new repo
      tags:
      - repos
  /repos/{id}:
    delete:
      description: delete repo
      parameters:
      - description: id for the repository
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrResponse'
      summary: Delete a repo
      tags:
      - repos
    put:
      consumes:
      - multipart/form-data
      description: upload to repo
      parameters:
      - description: id for the repository
        in: path
        name: id
        required: true
        type: string
      - description: files to upload to this reposiutory
        in: formData
        name: file_upload
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrResponse'
      summary: Upload files to a repo
      tags:
      - repos
  /repos/{id}/comps:
    delete:
      description: delete4 rpm comps
      parameters:
      - description: id for the repository
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrResponse'
      summary: Delete the RPM comps file
      tags:
      - repos
    put:
      description: push rpm comps
      parameters:
      - description: id for the repository
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrResponse'
      summary: Push a RPM comps file
      tags:
      - repos
  /repos/{id}/key:
    delete:
      description: delete repo key
      parameters:
      - description: id for the repository
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrResponse'
      summary: Delete key for a repo
      tags:
      - repos
    get:
      description: get repo key
      parameters:
      - description: id for the repository
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.fullKeyResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrResponse'
      summary: Get key for a repo
      tags:
      - repos
    put:
      description: set repo key
      parameters:
      - description: id for the repository
        in: path
        name: id
        required: true
        type: string
      - description: options for the new repository
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/types.CreateRepoPayload'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrResponse'
      summary: Set key for a repo
      tags:
      - repos
  /repos/{id}/resign:
    post:
      description: resign repo packages
      parameters:
      - description: id for the repository
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrResponse'
      summary: Resign packages in a repo
      tags:
      - repos
  /repos/{id}/rpms:
    get:
      description: rpms in repo
      parameters:
      - description: id for the repository
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.RpmResponse'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrResponse'
      summary: Get list of RPMs in a repo
      tags:
      - repos
  /repos/{id}/rpms/{rpmID}:
    delete:
      description: delete rpm
      parameters:
      - description: id for the repository
        in: path
        name: id
        required: true
        type: string
      - description: rpm id in the repository
        in: path
        name: rpmID
        required: true
        type: string
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrResponse'
      summary: Delete RPM in a repo
      tags:
      - repos
securityDefinitions:
  "":
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
