// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ReposColumns holds the columns for the "repos" table.
	ReposColumns = []*schema.Column{
		{Name: "oid", Type: field.TypeString, Unique: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"rpm", "ostree"}},
	}
	// ReposTable holds the schema information for the "repos" table.
	ReposTable = &schema.Table{
		Name:       "repos",
		Columns:    ReposColumns,
		PrimaryKey: []*schema.Column{ReposColumns[0]},
	}
	// RpmPackagesColumns holds the columns for the "rpm_packages" table.
	RpmPackagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "epoch", Type: field.TypeInt},
		{Name: "version", Type: field.TypeString},
		{Name: "release", Type: field.TypeString},
		{Name: "arch", Type: field.TypeString},
		{Name: "file_path", Type: field.TypeString},
		{Name: "repo_rpms", Type: field.TypeString, Nullable: true},
	}
	// RpmPackagesTable holds the schema information for the "rpm_packages" table.
	RpmPackagesTable = &schema.Table{
		Name:       "rpm_packages",
		Columns:    RpmPackagesColumns,
		PrimaryKey: []*schema.Column{RpmPackagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "rpm_packages_repos_rpms",
				Columns:    []*schema.Column{RpmPackagesColumns[7]},
				RefColumns: []*schema.Column{ReposColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "rpmpackage_file_path_repo_rpms",
				Unique:  true,
				Columns: []*schema.Column{RpmPackagesColumns[6], RpmPackagesColumns[7]},
			},
			{
				Name:    "rpmpackage_name_epoch_version_release_arch",
				Unique:  true,
				Columns: []*schema.Column{RpmPackagesColumns[1], RpmPackagesColumns[2], RpmPackagesColumns[3], RpmPackagesColumns[4], RpmPackagesColumns[5]},
			},
		},
	}
	// SigningKeysColumns holds the columns for the "signing_keys" table.
	SigningKeysColumns = []*schema.Column{
		{Name: "oid", Type: field.TypeString, Unique: true},
		{Name: "private_key", Type: field.TypeString},
		{Name: "public_key", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
	}
	// SigningKeysTable holds the schema information for the "signing_keys" table.
	SigningKeysTable = &schema.Table{
		Name:       "signing_keys",
		Columns:    SigningKeysColumns,
		PrimaryKey: []*schema.Column{SigningKeysColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ReposTable,
		RpmPackagesTable,
		SigningKeysTable,
	}
)

func init() {
	RpmPackagesTable.ForeignKeys[0].RefTable = ReposTable
}
