basePath: /api
definitions:
  ent.Repo:
    properties:
      edges:
        $ref: '#/definitions/ent.RepoEdges'
        description: |-
          Edges holds the relations/edges for other nodes in the graph.
          The values are being populated by the RepoQuery when eager-loading is set.
      id:
        description: ID of the ent.
        type: string
      type:
        description: Type holds the value of the "type" field.
        type: string
    type: object
  ent.RepoEdges:
    properties:
      rpms:
        description: Rpms holds the value of the rpms edge.
        items:
          $ref: '#/definitions/ent.RpmPackage'
        type: array
    type: object
  ent.RpmPackage:
    properties:
      arch:
        description: Arch holds the value of the "arch" field.
        type: string
      edges:
        $ref: '#/definitions/ent.RpmPackageEdges'
        description: |-
          Edges holds the relations/edges for other nodes in the graph.
          The values are being populated by the RpmPackageQuery when eager-loading is set.
      epoch:
        description: Epoch holds the value of the "epoch" field.
        type: string
      file_path:
        description: FilePath holds the value of the "file_path" field.
        type: string
      id:
        description: ID of the ent.
        type: integer
      name:
        description: Name holds the value of the "name" field.
        type: string
      release:
        description: Release holds the value of the "release" field.
        type: string
      version:
        description: Version holds the value of the "version" field.
        type: string
    type: object
  ent.RpmPackageEdges:
    properties:
      repo:
        $ref: '#/definitions/ent.Repo'
        description: Repo holds the value of the repo edge.
    type: object
  main.ErrResponse:
    properties:
      code:
        description: application-specific error code
        type: integer
      error:
        description: application-level error message, for debugging
        type: string
      status:
        description: user-level status message
        type: string
    type: object
  main.createRepoPayload:
    properties:
      id:
        type: string
      type:
        enum:
        - rpm
        - ostree
        type: string
    required:
    - id
    - type
    type: object
info:
  contact: {}
  description: A modern package delivery server.
  license:
    name: GPL3
    url: https://choosealicense.com/licenses/gpl-3.0/
  title: Subatomic
  version: "1.0"
paths:
  /repos:
    get:
      description: get repos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ent.Repo'
            type: array
      summary: Get all repos
      tags:
      - repos
    post:
      consumes:
      - application/json
      description: create repo
      parameters:
      - description: options for the new repository
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.createRepoPayload'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.ErrResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/main.ErrResponse'
      summary: Create a new repo
      tags:
      - repos
  /repos/{id}:
    delete:
      description: delete repo
      parameters:
      - description: id for the repository
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.ErrResponse'
      summary: Delete a repo
      tags:
      - repos
    put:
      consumes:
      - multipart/form-data
      description: upload to repo
      parameters:
      - description: id for the repository
        in: path
        name: id
        required: true
        type: string
      - description: files to upload to this reposiutory
        in: formData
        name: file_upload
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.ErrResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.ErrResponse'
      summary: Upload files to a repo
      tags:
      - repos
  /repos/{id}/rpms:
    get:
      description: rpms in repo
      parameters:
      - description: id for the repository
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.ErrResponse'
      summary: Get list of RPMs in a repo
      tags:
      - repos
securityDefinitions:
  "":
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
