name: Package

on:
  push:
    paths:
      - subatomic-cli/**/*
    branches: [main]
  workflow_dispatch:

jobs:
  anda:
    uses: andaman-common-pkgs/github-actions/.github/workflows/anda-rpm.yml@main
    with:
      name: "subatomic"
      subatomicServer: "https://subatomic.fyralabs.com"
      subatomicRepo: ad37
      mockConfig: anda-37-x86_64
      mockConfigPackage: anda-mock-configs
      upload: true
    secrets:
      subatomicToken: ${{ secrets.SUBATOMIC_TOKEN }}
